spring:
  jpa:
    hibernate:
      ddl-auto: update
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect # Allows Hibernate to generate SQL optimized for a particular DBMS
  datasource:
    url: jdbc:postgresql://localhost:5432/project_management
    username: postgres
    password: admin
  mvc:
    favicon:
      enabled: false
server:
  port: 8080
  contextPath: /context-path
logging:
  file: projectmanagement.log
